server:
  port: 9999
  undertow:
    direct-buffers: true
    io-threads: 4
    worker-threads: 160
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/**/*Mapper.xml
    - classpath*:com/itfenbao/gadmins/**/*Mapper.xml
  configuration:
    auto-mapping-behavior: FULL
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
api-access:
  admin:
    open: true
    secret: SKxnWUIfGwg1V@mB
  app:
    open: false
HASOR_DATAQL_FX_PAGE_DIALECT: mysql